Pager augmenetation
boki1/eugene pull request #19
Opened 2022-01-17 20:18 UTC by boki1

# Description
Refactor the Pager module. Make components based on `Policy` (e.g `StackAllocator` for `Page` allocation), which improves the modularity of the design and enables the development of the VL entry component.

# Test suite
```
. tools/env.sh
eu config && eu test +runtest
```

# Environment
Using gcc (GCC) 11.1.0 on a x86_64 machine with GNU/Linux.

--------------------

#### This PR makes changes which ...

- [x] are thoroughly tested
- [ ] are well documented

2022-01-18 17:46 UTC, StoyanTinchev commented
conversion from 'internal::storage::Position' (aka 'unsigned long') to signed type 'std::vector<int>::value_type' (aka 'int')

```
			b.push_back(Position(dist128(rng)));
```
								
[src/core/storage/btree/Node.cpp](https://github.com/boki1/eugene/blob/54cc673081ec08d57cf824513b86734707cf2516/src/core/storage/btree/Node.cpp#L38) (Line 38)

2022-01-19 07:19 UTC, StoyanTinchev commented
Here, 144 and 138 rows are narrowing conversion from `uint32_t` to signed type `std::vector<int>` (aka `int`)

```
		l.m_vals.push_back(i);
```
								
[src/core/storage/btree/Node.cpp](https://github.com/boki1/eugene/blob/54cc673081ec08d57cf824513b86734707cf2516/src/core/storage/btree/Node.cpp#L145) (Line 145)

2022-01-19 07:25 UTC, StoyanTinchev requested changes
Please consider the comments that I left (aka. good job)

2022-01-19 07:25 UTC, StoyanTinchev commented on src/core/storage/Pager.cpp
> +#include <algorithm>
unused

2022-01-19 07:25 UTC, StoyanTinchev commented on src/core/storage/Pager.cpp
> +#include <filesystem>
unused

2022-01-25 10:27 UTC, StoyanTinchev approved these changes
Just declare that function with [[nodiscard]]. Overall - good job!

2022-01-25 10:27 UTC, StoyanTinchev commented on src/core/storage/Pager.h
> +	constexpr bool has_allocated(const Position pos) const noexcept {
Can be marked [[nodiscard]]

2022-01-25 11:17 UTC, boki1 commented on src/core/storage/Pager.h
> +	constexpr bool has_allocated(const Position pos) const noexcept {
Yup.

2022-01-25 14:44 UTC, merged