Btree crud
boki1/eugene pull request #21
Opened 2022-02-13 00:32 UTC by boki1

# Description
Implement remove and update. Refactor searching to keep the traversed path as `TreePath` and reuse it during operations.

# Test suite
```
. tools/env.sh
eu config && eu test +runtest
```

# Environment
Using gcc (GCC) 11.1.0 on a x86_64 machine with GNU/Linux.

--------------------

#### This PR makes changes which ...

- [x] are thoroughly tested
- [x] are well documented

2022-02-14 13:01 UTC, StoyanTinchev requested changes
Overall - nice, just fix the requested changes or for some of them explain to me their purpose.

2022-02-14 13:01 UTC, StoyanTinchev commented on src/core/SizeMetrics.h
>  #pragma once
Why this file is empty?

2022-02-14 13:01 UTC, StoyanTinchev commented on .gitmodules
> +	url = https://github.com/Felerius/btree-generator
Equal with the previous module, I think?

2022-02-14 13:01 UTC, StoyanTinchev commented on src/core/Util.h
> +	constexpr const char *str() const noexcept { return m_str; }
Should be marked with `[[nodiscard]]`

2022-02-14 13:01 UTC, StoyanTinchev commented on src/core/storage/Pager.h
> +	void free(const Position) {
Are you sure about that method?

2022-02-14 13:01 UTC, StoyanTinchev commented on src/core/storage/Pager.h
> +	constexpr bool has_allocated(const Position pos) const noexcept {
should be marked `[[nodiscard]]`

2022-02-14 13:01 UTC, StoyanTinchev commented on src/core/storage/Pager.h
> +    [[nodiscard]] constexpr bool has_allocated(const Position) { return true; }
Wow, again - what is the purpose?

2022-02-14 13:01 UTC, StoyanTinchev commented on src/core/storage/Pager.h
> +	[[nodiscard]] static CacheEvictionResult evict(PageCache<LRUCache> &cache) {
Never used?

2022-02-14 13:01 UTC, StoyanTinchev commented on src/core/storage/Pager.h
> +		m_disk.seekp(pos);
Here and 263 line are conversions from `unsigned long` to signed type `std::streamoff` (aka `long`)

2022-02-14 13:01 UTC, StoyanTinchev commented on src/core/storage/btree/Config.h
> +	using PageEvictionPolicy = LRUCache;
These policies aren't used

2022-02-14 13:40 UTC, boki1 commented on src/core/SizeMetrics.h
>  #pragma once
Because we don't need it anymore. I'll delete it :smile:

2022-02-14 13:40 UTC, boki1 commented on src/core/storage/Pager.h
> +	constexpr bool has_allocated(const Position pos) const noexcept {
Yup.

2022-02-14 13:40 UTC, boki1 commented on src/core/Util.h
> +	constexpr const char *str() const noexcept { return m_str; }
Yup.

2022-02-14 13:44 UTC, boki1 commented on src/core/storage/Pager.h
> +	void free(const Position) {
Yes, it needs to be implemented, in order to conform to the generic allocator API, however it is not applicable in this particular one.

2022-02-14 13:44 UTC, boki1 commented on src/core/storage/Pager.h
> +	constexpr bool has_allocated(const Position pos) const noexcept {
:+1:

2022-02-14 13:44 UTC, boki1 commented on src/core/storage/Pager.h
> +    [[nodiscard]] constexpr bool has_allocated(const Position) { return true; }
Hm, that's an error. I have forgotten to implement this. :smiley:

2022-02-14 13:44 UTC, boki1 commented on src/core/storage/Pager.h
> +	[[nodiscard]] static CacheEvictionResult evict(PageCache<LRUCache> &cache) {
It is used.

2022-02-14 13:44 UTC, boki1 commented on src/core/storage/btree/Config.h
> +	using PageEvictionPolicy = LRUCache;
They are used in `Btree.h` which defines the `Pager<>` specific type

2022-02-28 07:51 UTC, StoyanTinchev requested changes
Please, don't resolve conversations before really to commit and fix the specific bug.

2022-02-28 07:51 UTC, StoyanTinchev commented on src/core/Util.h
> +	constexpr const char *str() const noexcept { return m_str; }
Has not yet been marked as`[[nodiscard]]`

2022-02-28 07:51 UTC, StoyanTinchev commented on src/core/storage/Pager.h
> +	constexpr bool has_allocated(const Position pos) const noexcept {
Has not yet been marked as `[[nodiscard]]`

2022-02-28 07:51 UTC, StoyanTinchev commented on src/core/storage/Pager.h
> +    [[nodiscard]] constexpr bool has_allocated(const Position) { return true; }
When you will implement that?

2022-02-28 08:18 UTC, StoyanTinchev approved these changes
Please consider to add `[[nodiscard]]`

2022-03-04 08:08 UTC, merged